/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';
import { ConfigService } from './config.service';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  public rootUrl: string;

  constructor(private configService: ConfigService) {
    // Ensure safe access to configuration
    this.rootUrl = this.configService.readConfig()?.API_URL  || '';
  }
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
