/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUnit } from '../../models/api-response-unit';

export interface SetMessageToSeen$Params {
  chat_id: string;
}

export function setMessageToSeen(http: HttpClient, rootUrl: string, params: SetMessageToSeen$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUnit>> {
  const rb = new RequestBuilder(rootUrl, setMessageToSeen.PATH, 'patch');
  if (params) {
    rb.query('chat_id', params.chat_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUnit>;
    })
  );
}

setMessageToSeen.PATH = '/messages';
