/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseString } from '../models/api-response-string';
import { getHealthInfo } from '../fn/health-check-controller/get-health-info';
import { GetHealthInfo$Params } from '../fn/health-check-controller/get-health-info';

@Injectable({ providedIn: 'root' })
export class HealthCheckControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHealthInfo()` */
  static readonly GetHealthInfoPath = '/actuator2/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHealthInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHealthInfo$Response(params?: GetHealthInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseString>> {
    return getHealthInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHealthInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHealthInfo(params?: GetHealthInfo$Params, context?: HttpContext): Observable<ApiResponseString> {
    return this.getHealthInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseString>): ApiResponseString => r.body)
    );
  }

}
