/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatPreviewResponse } from '../models/chat-preview-response';
export interface ApiResponseListChatPreviewResponse {
  data?: Array<ChatPreviewResponse>;
  message?: string;
  metadata?: {
};
  status?: number;
}
