/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponse } from '../models/user-response';
export interface ApiResponseListUserResponse {
  data?: Array<UserResponse>;
  message?: string;
  metadata?: {
};
  status?: number;
}
