/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageRequest {
  chat_id?: string;
  chat_name?: string;
  content?: string;
  receiver_id?: string;
  sender_id?: string;
  type?: number;
}
