/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  attachment_file?: Array<string>;
  file_name?: string;
  content?: string;
  created_date?: string;
  id?: string;
  receiver_id?: string;
  sender_id?: string;
  state?: number;
  type?: number;
}
